import { NextResponse } from 'next/server';
import connectDB from '@/lib/db';
import Book from '@/models/Book';

const books = [
  { title: "The Alchemist", author: "Paulo Coelho", description: "A magical story about following your dreams.", price: 299, originalPrice: 399, cover: "https://covers.openlibrary.org/b/id/8739161-L.jpg", category: "Fiction", rating: 4.8, reviews: 2341, deliveryTime: "10 mins", pages: 208, language: "English", publisher: "HarperCollins" },
  { title: "Atomic Habits", author: "James Clear", description: "An easy and proven way to build good habits and break bad ones.", price: 499, originalPrice: 699, cover: "https://covers.openlibrary.org/b/id/10909258-L.jpg", category: "Self Help", rating: 4.9, reviews: 5621, deliveryTime: "10 mins", pages: 320, language: "English", publisher: "Penguin" },
  { title: "Harry Potter and the Sorcerer's Stone", author: "J.K. Rowling", description: "A young boy discovers he is a wizard on his 11th birthday.", price: 399, originalPrice: 599, cover: "https://covers.openlibrary.org/b/id/10110415-L.jpg", category: "Fantasy", rating: 4.9, reviews: 8921, deliveryTime: "10 mins", pages: 309, language: "English", publisher: "Scholastic" },
  { title: "The Great Gatsby", author: "F. Scott Fitzgerald", description: "A story of wealth, love, and the American Dream in the 1920s.", price: 199, originalPrice: 299, cover: "https://covers.openlibrary.org/b/id/11905682-L.jpg", category: "Fiction", rating: 4.5, reviews: 3241, deliveryTime: "10 mins", pages: 180, language: "English", publisher: "Scribner" },
  { title: "Sapiens", author: "Yuval Noah Harari", description: "A brief history of humankind from ancient times to the present.", price: 599, originalPrice: 799, cover: "https://covers.openlibrary.org/b/id/8739165-L.jpg", category: "Non Fiction", rating: 4.7, reviews: 4521, deliveryTime: "10 mins", pages: 443, language: "English", publisher: "Harper" },
  { title: "The Lean Startup", author: "Eric Ries", description: "How constant innovation creates radically successful businesses.", price: 449, originalPrice: 599, cover: "https://covers.openlibrary.org/b/id/8739166-L.jpg", category: "Business", rating: 4.6, reviews: 2100, deliveryTime: "10 mins", pages: 336, language: "English", publisher: "Crown" },
  { title: "To Kill a Mockingbird", author: "Harper Lee", description: "A powerful story of racial injustice and moral growth in the American South.", price: 249, originalPrice: 349, cover: "https://covers.openlibrary.org/b/id/8739167-L.jpg", category: "Fiction", rating: 4.8, reviews: 6721, deliveryTime: "10 mins", pages: 281, language: "English", publisher: "Grand Central" },
  { title: "Rich Dad Poor Dad", author: "Robert Kiyosaki", description: "What the rich teach their kids about money that the poor do not.", price: 349, originalPrice: 499, cover: "https://covers.openlibrary.org/b/id/8739168-L.jpg", category: "Business", rating: 4.5, reviews: 3891, deliveryTime: "10 mins", pages: 207, language: "English", publisher: "Plata Publishing" },
  { title: "The Psychology of Money", author: "Morgan Housel", description: "Timeless lessons on wealth, greed, and happiness.", price: 399, originalPrice: 549, cover: "https://covers.openlibrary.org/b/id/10527843-L.jpg", category: "Business", rating: 4.8, reviews: 4231, deliveryTime: "10 mins", pages: 256, language: "English", publisher: "Harriman House" },
  { title: "1984", author: "George Orwell", description: "A dystopian novel about a totalitarian society and one man's rebellion.", price: 199, originalPrice: 299, cover: "https://covers.openlibrary.org/b/id/8739171-L.jpg", category: "Fiction", rating: 4.7, reviews: 7821, deliveryTime: "10 mins", pages: 328, language: "English", publisher: "Signet Classic" },
  { title: "Think and Grow Rich", author: "Napoleon Hill", description: "The landmark bestseller on the secrets of success and achievement.", price: 299, originalPrice: 399, cover: "https://covers.openlibrary.org/b/id/8739172-L.jpg", category: "Self Help", rating: 4.6, reviews: 3421, deliveryTime: "10 mins", pages: 238, language: "English", publisher: "Sound Wisdom" },
  { title: "The Hobbit", author: "J.R.R. Tolkien", description: "A hobbit embarks on an unexpected journey with a group of dwarves.", price: 349, originalPrice: 499, cover: "https://covers.openlibrary.org/b/id/8739173-L.jpg", category: "Fantasy", rating: 4.8, reviews: 5621, deliveryTime: "10 mins", pages: 310, language: "English", publisher: "Houghton Mifflin" },
  { title: "Deep Work", author: "Cal Newport", description: "Rules for focused success in a distracted world.", price: 399, originalPrice: 549, cover: "https://covers.openlibrary.org/b/id/8739174-L.jpg", category: "Self Help", rating: 4.7, reviews: 2891, deliveryTime: "10 mins", pages: 296, language: "English", publisher: "Grand Central" },
  { title: "Zero to One", author: "Peter Thiel", description: "Notes on startups, or how to build the future.", price: 449, originalPrice: 599, cover: "https://covers.openlibrary.org/b/id/8739175-L.jpg", category: "Business", rating: 4.6, reviews: 2341, deliveryTime: "10 mins", pages: 224, language: "English", publisher: "Crown" },
  { title: "The 7 Habits of Highly Effective People", author: "Stephen Covey", description: "Powerful lessons in personal change for professional and personal effectiveness.", price: 399, originalPrice: 549, cover: "https://covers.openlibrary.org/b/id/8739176-L.jpg", category: "Self Help", rating: 4.7, reviews: 4121, deliveryTime: "10 mins", pages: 381, language: "English", publisher: "Simon & Schuster" },
  { title: "Dune", author: "Frank Herbert", description: "An epic tale of politics, religion and survival on a desert planet.", price: 499, originalPrice: 699, cover: "https://covers.openlibrary.org/b/id/8739177-L.jpg", category: "Fantasy", rating: 4.8, reviews: 4521, deliveryTime: "10 mins", pages: 412, language: "English", publisher: "Ace" },
  { title: "The Subtle Art of Not Giving a F*ck", author: "Mark Manson", description: "A counterintuitive approach to living a good life.", price: 349, originalPrice: 499, cover: "https://covers.openlibrary.org/b/id/8739178-L.jpg", category: "Self Help", rating: 4.5, reviews: 5231, deliveryTime: "10 mins", pages: 224, language: "English", publisher: "HarperOne" },
  { title: "A Brief History of Time", author: "Stephen Hawking", description: "A landmark volume in science writing that explores the universe.", price: 349, originalPrice: 499, cover: "https://covers.openlibrary.org/b/id/8739179-L.jpg", category: "Non Fiction", rating: 4.7, reviews: 3821, deliveryTime: "10 mins", pages: 212, language: "English", publisher: "Bantam" },
  { title: "The Midnight Library", author: "Matt Haig", description: "Between life and death there is a library with infinite possibilities.", price: 399, originalPrice: 549, cover: "https://covers.openlibrary.org/b/id/10909260-L.jpg", category: "Fiction", rating: 4.6, reviews: 3241, deliveryTime: "10 mins", pages: 288, language: "English", publisher: "Viking" },
  { title: "Educated", author: "Tara Westover", description: "A memoir about a woman who grows up in a survivalist family and goes on to earn a PhD.", price: 449, originalPrice: 599, cover: "https://covers.openlibrary.org/b/id/8739181-L.jpg", category: "Non Fiction", rating: 4.8, reviews: 4121, deliveryTime: "10 mins", pages: 334, language: "English", publisher: "Random House" },
  { title: "The Monk Who Sold His Ferrari", author: "Robin Sharma", description: "A fable about fulfilling your dreams and reaching your destiny.", price: 299, originalPrice: 399, cover: "https://covers.openlibrary.org/b/id/8739182-L.jpg", category: "Self Help", rating: 4.5, reviews: 2891, deliveryTime: "10 mins", pages: 198, language: "English", publisher: "HarperCollins" },
  { title: "The Da Vinci Code", author: "Dan Brown", description: "A symbologist uncovers a conspiracy hidden in the works of Leonardo Da Vinci.", price: 349, originalPrice: 499, cover: "https://covers.openlibrary.org/b/id/8739183-L.jpg", category: "Fiction", rating: 4.5, reviews: 6721, deliveryTime: "10 mins", pages: 454, language: "English", publisher: "Doubleday" },
  { title: "Ikigai", author: "Hector Garcia", description: "The Japanese secret to a long and happy life.", price: 299, originalPrice: 399, cover: "https://covers.openlibrary.org/b/id/8739184-L.jpg", category: "Self Help", rating: 4.6, reviews: 3421, deliveryTime: "10 mins", pages: 194, language: "English", publisher: "Penguin" },
  { title: "The Hitchhiker's Guide to the Galaxy", author: "Douglas Adams", description: "A comedic science fiction series following the misadventures of Arthur Dent.", price: 299, originalPrice: 399, cover: "https://covers.openlibrary.org/b/id/8739185-L.jpg", category: "Fantasy", rating: 4.7, reviews: 4821, deliveryTime: "10 mins", pages: 224, language: "English", publisher: "Pan Books" },
  { title: "Becoming", author: "Michelle Obama", description: "An intimate memoir by the former First Lady of the United States.", price: 499, originalPrice: 699, cover: "https://covers.openlibrary.org/b/id/8739186-L.jpg", category: "Non Fiction", rating: 4.8, reviews: 5621, deliveryTime: "10 mins", pages: 426, language: "English", publisher: "Crown" },
  { title: "The Power of Now", author: "Eckhart Tolle", description: "A guide to spiritual enlightenment and living in the present moment.", price: 349, originalPrice: 499, cover: "https://covers.openlibrary.org/b/id/8739187-L.jpg", category: "Self Help", rating: 4.6, reviews: 3121, deliveryTime: "10 mins", pages: 236, language: "English", publisher: "New World Library" },
  { title: "Good to Great", author: "Jim Collins", description: "Why some companies make the leap and others don't.", price: 449, originalPrice: 599, cover: "https://covers.openlibrary.org/b/id/8739188-L.jpg", category: "Business", rating: 4.6, reviews: 2341, deliveryTime: "10 mins", pages: 300, language: "English", publisher: "HarperBusiness" },
  { title: "The Courage to Be Disliked", author: "Ichiro Kishimi", description: "How to free yourself, change your life and achieve real happiness.", price: 349, originalPrice: 499, cover: "https://covers.openlibrary.org/b/id/8739189-L.jpg", category: "Self Help", rating: 4.7, reviews: 2891, deliveryTime: "10 mins", pages: 288, language: "English", publisher: "Atria" },
  { title: "Steve Jobs", author: "Walter Isaacson", description: "The exclusive biography of Apple's co-founder and visionary.", price: 599, originalPrice: 799, cover: "https://covers.openlibrary.org/b/id/8739190-L.jpg", category: "Non Fiction", rating: 4.7, reviews: 4521, deliveryTime: "10 mins", pages: 656, language: "English", publisher: "Simon & Schuster" },
  { title: "The Jungle Book", author: "Rudyard Kipling", description: "The adventures of Mowgli, a boy raised by wolves in the Indian jungle.", price: 199, originalPrice: 299, cover: "https://covers.openlibrary.org/b/id/8739191-L.jpg", category: "Fiction", rating: 4.5, reviews: 2341, deliveryTime: "10 mins", pages: 208, language: "English", publisher: "Macmillan" },
];

export async function GET() {
  try {
    await connectDB();
    await Book.deleteMany({});
    await Book.insertMany(books);
    return NextResponse.json({ message: 'Database seeded with 30 books!' });
  } catch (error) {
  console.error(error); // 👈 add this
  return NextResponse.json({ error: 'Seeding failed' }, { status: 500 });
}
}